### ISSUE TITLE
bug on responsive

### ISSUE THREAD

**Issue by yussan** [ymg-team/byymg-web#9]
ref : https://byidmore.com/ and scroll to the team 

problem : 
<img width="610" alt="screen shot 2018-10-09 at 11 05 50" src="https://user-images.githubusercontent.com/4264672/46646258-6d694480-cbb3-11e8-9c79-24a8bb262423.png">

It must be : 
list view or grid.. do not overlap.

we are using gridflex, you can read this reference https://gridlex.devlint.fr/

**Comment by harryandriyan** [comment]
I'll handle this

**Comment by yussan** [comment]
thank's go ahead :D , @harryandriyan i just updated issue, added refence of gridflex as css framework https://gridlex.devlint.fr/
